### ISSUE TITLE
Getting exception after updating to 2.0.0 version

### ISSUE THREAD

**Issue by AnantVikramSinghTR** [coveooss/spring-boot-parameter-store-integration#166]
Hi,

I had to update my project to use the latest version of spring-boot-parameter-store-integration which is 2.0.0 in order to remove following vulnerability:
https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2436751

But now I am getting following exception and a test case is failing:
java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:143
        Caused by: java.lang.IllegalStateException at SpringApplication.java:809
            Caused by: java.lang.NoClassDefFoundError at ParameterStorePropertySourceEnvironmentPostProcessor.java:37
                Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:641
                
                
Can you please help me with this vulnerability ?
